Resources:
    CPUAlarmHigh:
        Type: 'AWS::CloudWatch::Alarm'
        Properties:
            Namespace: AWS/DynamoDB
            MetricName: SystemErrors
            Dimensions:
              - Name: TableName
                Value: test
            Statistic: Sum
            Period: 70
            EvaluationPeriods: 2
            ComparisonOperator: GreaterThanOrEqualToThreshold
            Threshold: 1
